services:
  puttable:
    build:
      context: .
      args:
        PUTTABLE_APP_VERSION: "local"
    ports:
      - "5173:3000"
    env_file:
      - .env.supabase-anon-key # This file is supposed to contain the supabase anon as PUBLIC_SUPABASE_ANON_KEY
    environment:
      - PUBLIC_SUPABASE_URL=http://api.supabase.internal:8000
      - BASE_PATH=http://localhost:5173/
    depends_on:
      - keycloak
    networks:
      - supabase_network_puttable

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/puttable-realm.json:/opt/keycloak/data/import/puttable-realm.json
      - ./keycloak/themes:/opt/keycloak/themes
    networks:
      - supabase_network_puttable

  dns:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
    networks:
      - supabase_network_puttable

networks:
  supabase_network_puttable:
    external: true