services:
  puttable:
    build: .
    ports:
      - "5173:5173"
    environment:
      - PUBLIC_SUPABASE_URL=http://192.168.179.65:54321
      - PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_AUTH_KEYCLOAK_CLIENT_ID=supabase-dev
      - SUPABASE_AUTH_KEYCLOAK_SECRET=Fg3UHxrIFjPbZX8gS6zxUraa9l0lW4sw
      - SUPABASE_AUTH_KEYCLOAK_URL=https://auth.g8ways.de/realms/puttable
      - PUBLIC_SUPABASE_AUTH_KEYCLOAK_REDIRECT_URI=http://192.168.179.65:5173/auth/v1/callback
      - PUBLIC_SITE_BASE_URL=http://192.168.179.65:5173
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5173
      - BASE_PATH=http://192.168.179.65:5173/
      - CHECK_ORIGIN=false
