apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "puttable.labels" . | nindent 4 }}
    helm.sh/chart: {{ include "puttable.chart" . }}
  name: {{ template "puttable.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "puttable.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "puttable.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "puttable.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PUBLIC_SUPABASE_URL
              value: {{ .Values.puttable.supabase.url | quote }}
            - name: PUBLIC_SUPABASE_ANON_KEY
              {{- if .Values.puttable.supabase.apiKey.secret }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.puttable.supabase.apiKey.secret.secretKey }}
                  name: {{ .Values.puttable.supabase.apiKey.secret.secretName }}
              {{ else }}
              value: {{ .Values.puttable.supabase.apiKey.value }}
              {{- end }}
            - name: PUBLIC_SITE_BASE_URL
              value: {{ .Values.puttable.baseUrl }}
            - name: PUBLIC_SUPABASE_AUTH_KEYCLOAK_REDIRECT_URI
              value: {{ .Values.puttable.keycloak.redirectUri }}
            - name: SUPABASE_AUTH_KEYCLOAK_CLIENT_ID
              value: {{ .Values.puttable.keycloak.clientId }}
            - name: SUPABASE_AUTH_KEYCLOAK_SECRET
              {{- if .Values.puttable.keycloak.clientSecret.secret }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.puttable.keycloak.clientSecret.secret.secretKey }}
                  name: {{ .Values.puttable.keycloak.clientSecret.secret.secretName }}
              {{ else }}
              value: {{ .Values.puttable.keycloak.clientSecret.value }}
              {{- end }}
            - name: SUPABASE_AUTH_KEYCLOAK_URL
              value: {{ .Values.puttable.keycloak.realmUrl }}
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}

            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext}}
      securityContext:
        {{ toDate . | nindent 8 }}
      {{- end }}
